#!/bin/bash

cd docs/

# ============================================
# Clean
# ============================================
rm -rf _build

# ============================================
# Generate autodoc
# ============================================
sphinx-apidoc -M -f -e --ext-autodoc --ext-viewcode -o . "../pyDSA_core"

# # ============================================
# # Clean autogenerated doc
# # ============================================
# printf "Cleaning auto-generated api doc... "
# # Classes
# sed -i 's/PyFields\.core\.points module/Points class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.profile module/Profile class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.field module/Field class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.vectorfield module/VectorField class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.scalarfield module/ScalarField class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.temporalfields module/TemporalFields class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.fields module/Fields class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.temporalscalarfields module/TemporalScalarFields class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.temporalvectorfields module/TemporalVectorFields class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.spatialfields module/SpatialFields class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.spatialscalarfields module/SpatialScalarFields class/g' PyFields.*.rst
# sed -i 's/PyFields\.core\.spatialvectorfields module/SpatialVectorFields class/g' PyFields.*.rst
# # Utilities
# sed -i 's/PyFields\.utils\.units module/Units module/g' PyFields.*.rst
# # Modules
# sed -i 's/PyFields\.\([^.]*\)\.\1 module/\u\1 module/g' PyFields.*.rst
# sed -i 's/PyFields\.\([^.]*\)\.\([^.]*\) module/\u\1.\2 module/g' PyFields.*.rst
# # Packages
# sed -i 's/PyFields\.\([^.]*\) package/\u\1 package/g' PyFields.*.rst
# sed -i 's/Submodules\n----------//g' PyFields.*.rst
# sed -i '/^Submodules/ { N ; N ; d }' PyFields.*.rst
# printf "Done\n"

# ============================================
# Make doc with sphinx
# ============================================
make html
